import ButtonLink from "@/components/buttonLink/buttonLink";
//import sideBarStyle from "../styles/sidebar.module.css";
import "../styles/globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>Wiki</title>
      </head>
      <body className="h-full">
        <div className="border border-slate-400 h-full float-left w-full">
          <SideBar></SideBar>
          <div className="bg-slate-800 h-full p-5 w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
function SideBar(){
  return <>
    <div className="p-0 m-0 border rounded-md min-w-60 h-full float-left bg-slate-700">
        <div className="bg-slate-900 p-2">
          <h1 className="text-center text-slate-50">Some Kind of Title</h1>
        </div>
        <div className="flex flex-col px-3">
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
        </div>
    </div>
  </>;
}
function MainView(){
  return <>
    <SideBar />
  </>;
}