import Header from "@/components/header/header";
import SideBar from "@/components/aside/aside";
import "../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>Wiki</title>
      </head>
      <body className="h-full bg-primary">
        <div className="w-full h-full flex flex-col">
          <Header />
          <div className="flex">
            <SideBar />
            <main className="p-5">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}