import ButtonLink from "@/components/buttonLink/buttonLink";
//import sideBarStyle from "../styles/sidebar.module.css";
import "../styles/globals.css";
import Header from "@/components/header/header";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>Wiki</title>
      </head>
      <body className="h-full bg-primary">
        <div className="w-full h-full flex flex-col">
          <Header />
          <div className="flex">
            <SideBar />
            <main className="p-5">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
function SideBar() {
  return <>
    <aside className="w-60 top-10 h-full min-w-60 float-left">
      <div className="fixed w-60 top-10 h-full bg-secondary border border-highlight min-w-60 float-left">
        <div className="bg-accent p-2">
          <h1 className="text-center text-slate-50">Some Kind of Title</h1>
        </div>
        <div className="flex flex-col px-3">
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
          <ButtonLink>Test</ButtonLink>
        </div>
      </div>
    </aside>
  </>;
}