name: Pull Request Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    check:
        name: Build Check
        runs-on: ubuntu-latest
        env:
          __source_path: wiki_build
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install Project 🔧
              run: npm run init

            - name: Check Linting 🔎
              run: npm run lint
            - name: Map
              run: node .

            - name: Check Build 🔧
              run: npm run build